name: YeahPhy
version: 1.0.0
main: io.yeah.yeahphy.Main

commands:
  player:
    description: get player's info.
    usage: /player [username]

  stat:
    description: set or show players stats
    usage: /stat <player> [stat] [set-value]